#!/usr/bin/env sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e alsamixer & ;;
	2) pactl set-sink-mute 0 toggle ;;
	4) pactl set-sink-volume 0 +5% >/dev/null 2>/dev/null ;;
	5) pactl set-sink-volume 0 -5% >/dev/null 2>/dev/null ;;
	3) pgrep -x dunst >/dev/null && notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change."
esac

vol=$(pactl list sinks | grep "Volume" | head -n 1 | awk '{print $5}' | sed 's/[^0-9]*//g')

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s %s%%\\n" "$icon" "$vol"
